name: dutchenko

services:
    dev:
        build:
            dockerfile: dev.dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-dev
        hostname: ${COMPOSE_PROJECT_NAME}-dev
        working_dir: /app
        tty: true
        volumes:
            - ./:/app
        ports:
            - '3000:3000'
